---
name: Dockerhub Readme
author: ms-jpq
description: |-
  sync Github <readme.md> with Dockerhub

inputs:
  username:
    required: True
    description: |-
      Dockerhub username

  password:
    required: True
    description: |-
      Dockerhub password

  readme:
    required: True
    description: |-
      path to readme markdown

  repository:
    required: True
    description: |-
      list of repositories to update
      (without username)

  replace_pattern:
    required: False
    description: |-
      if set, all occurences of "replace_pattern" 
      will be replaced with "replace_with"
    default: ''

  replace_with:
    required: False
    description: |-
      if set, all occurences of "replace_pattern" 
      will be replaced with "replace_with"
    default: ''

runs:
  using: docker
  image: "Dockerfile"
  env:
    DOCKER_USERNAME: "${{ inputs.username }}"
    DOCKER_PASSWORD: "${{ inputs.password }}"
  args:
    - "--readme"
    - "${{ inputs.readme }}"
    - "--repo"
    - "${{ inputs.repository }}"
    - "--replace-pattern"
    - "${{ inputs.replace_pattern }}"
    - "--replace-with"
    - "${{ inputs.replace_with }}"

branding:
  icon: anchor
  color: blue

